// <auto-generated />
namespace RubiconBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TagListaslistofstringsinBlogPost2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TagListaslistofstringsinBlogPost2));
        
        string IMigrationMetadata.Id
        {
            get { return "201810040810331_TagList as list of strings in BlogPost 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
